name: Build Filaments

on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
      - hotfix/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run ID-Tausch-Skript
        run: python scripts/change_id.py

      - name: Finde doppelte IDs und exportiere Mapping
        run: python scripts/find_duplicates.py

      - name: Commit generated JSON files to main branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git pull origin main
          git add temp_download/de_filaments.json temp_download/filaments.json temp_download/original_filaments.json temp_download/id_mapping.json
          git commit -m "Update generated JSON files [automated]" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
