name: Deploy Filaments

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create publish folder
        run: mkdir -p publish

      - name: Copy files to publish folder
        run: |
          cp templates/index.html publish/index.html
          cp templates/styles.css publish/styles.css
          cp temp_download/filaments.json publish/filaments.json
          cp materials.json publish/materials.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
