name: Deploy Filaments

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create publish folder
        run: mkdir -p publish

      - name: Copy files to publish folder
        run: |
          cp templates/index.html publish/index.html
          cp templates/styles.css publish/styles.css
          cp temp_download/filaments.json publish/filaments.json
          cp materials.json publish/materials.json

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: ./publish
